### ISSUE TITLE
0.1.0 Roadmap

### ISSUE THREAD

**Issue by NagaseIori** [NagaseIori/DyNode#1]
DyNode 0.1.0 版本的开发路线。

旨在还原、修复与增强 Dynamaker 的操作逻辑。

## Basics & Play

- [x] 谱面导入、预览与播放
- [x] 基本粒子效果
- [x] #2
- [x] 基本动画
- [x] 回放速度调整 https://github.com/NagaseIori/DyNode/commit/d6be00a074d99eee169c58452b9c920fb75feb38
  - 音调也被改变了...  fmod似乎没有支持不变调变速的方法？
- [x] 回放模式
  - 适于录制公开的模式

## UI

- [x] 谱面数据统计
- [x] 初始新建工程页面

## Editor

- [x] #4
  - [x] 可变段节拍
  - [x] BPM计算节拍线（变BPM谱面）
- [x] Note 数据显示
  - [x] 支持 Bar 显示
- [x] #3
- [x] Note 放置
  - [x] 正面 https://github.com/NagaseIori/DyNode/pull/6/commits/da57a81c2dfcd0bebdf0b3720b5f59be27810122
  - [x] 侧面
- [x] 单项选择、移动与三面编辑切换
  - [x] 正面 https://github.com/NagaseIori/DyNode/pull/6/commits/da57a81c2dfcd0bebdf0b3720b5f59be27810122
  - [x] 侧面
- [x] 谱面导出
  - [x] XML 格式 https://github.com/NagaseIori/DyNode/commit/7767a743d8eb0e4f899df5e861869cb3b56c39ce
    - [x] 自定义全局 Bar Per Minute 与 Offset
  - [x] DyN 格式
- [x] 谱面导入
  - [x] xml
- [x] 批量选择、移动
  - [x] 复制、剪切、粘贴
  - [x] 镜像
  - [x] 设置宽度
- [x] 方向键微调
- [x] 纵向网格线
  - ~~可变密度~~
- [x] 撤销 & 还原
- [x] 网格吸附
  - [x] 纵向
  - [x] 横向
- [x] 工程管理
- [x] Timing Points 编辑
- [x] 自动保存
